baseURL = 'https://cohub-hugo.netlify.app'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'Room Evolution'
 

  # Main Menu
  [[menu.Main]]
  name = "Галерея"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Возможности"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "О нас"
  url= "/about/"
  weight = 3
  [[menu.Main]]
  name = "Блог"
  url= "#blog"
  weight = 4
  [[menu.Main]]
  name = "Инвестиции"
  url= "#pricing"
  weight = 5
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Контакты"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  #[[menu.sitemap]]
  #name = "Privacy Policy"
  #url = "/privacy/"
  #weight = 1
  #[[menu.sitemap]]
  #name = "Terms"
  #url = "/terms/"
  #weight = 2

[params]
  # theme_overrides = "css/overrides.css"
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} Room Evolution"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.svg"
  footerlogo = "images/logo.svg"
  footerDescription = "Room Evolution - ваш надежный партнер халяльных инвестиций в недвижимость. Преумножайте свои сбережения с нами!"

  [params.address]
  email = "room_evo_halal@rambler.ru"
  openingDesc = "Свяжитесь с нами удобным для вас способом в любое время, мы постараемся ответить на все вопросы в течение 24 часов"
  openingHours = "Мы на связи с 9:00 до 19:00 каждый день"
  # phone = "+(448) 833 5272 332"

  # [params.map]
  # APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  # latitude = "45.4502528"
  # longitude = "-122.783407"
  # pinImage = "images/pin.png"

  # Social icons
  #[[params.social]]
  #icon = "ti-facebook"
  #url = "https://www.facebook.com/"
  #weight = 1
  #[[params.social]]
  #icon = "ti-twitter-alt"
  #url = "https://twitter.com/"
  #weight = 2
  [[params.social]]
  icon = "ti-location-arrow"
  url = "https://t.me/room_evo_halal"
  weight = 3
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/room_evo_halal"
  weight = 4
  [[params.social]]
  icon = "ti-youtube"
  url = "https://www.youtube.com/room_evo_halal"
  weight = 5
  
  
